In [10]:
import torch
import pandas as pd
import numpy as np

In [84]:
torch.set_printoptions(precision=4, sci_mode=False)

In [87]:
hw_pred = torch.load("../saved_models/trans_single_frame_12_27_hw/predictions/2022100213_3554.pt")
pos_pred = torch.load("../saved_models/trans_single_frame_12_12_pos/predictions/2022100213_3554.pt")
player_ids = np.load(f'/Users/scottmaran/Code/Python/bdb_2024/cleaned_data/seq_clipped_sorted_data/player_ids/2022100213_3554.npy').astype(np.int32)

In [80]:
hw_pred_2 = torch.load("../saved_models/trans_single_frame_12_12_pos/predictions/2022100213_3554.pt")

In [91]:
hw_pred[0]

tensor([    0.0001,     0.0041,     0.0000,     0.0009,     0.0215,     0.0289,
            0.0210,     0.1400,     0.3638,     0.1426,     0.0651,     0.2119,
            0.0000,     0.0000,     0.0000,     0.0000,     0.0000,     0.0000,
            0.0000,     0.0000,     0.0000,     0.0000,     0.0000],
       device='mps:0')

In [92]:
pos_pred[0]

tensor([    0.0000,     0.1783,     0.0622,     0.0454,     0.0149,     0.0513,
            0.0017,     0.1930,     0.0539,     0.1104,     0.1141,     0.1747,
            0.0000,     0.0000,     0.0000,     0.0000,     0.0000,     0.0000,
            0.0000,     0.0000,     0.0000,     0.0000,     0.0000],
       device='mps:0')

In [95]:
hw_pred_df.head()

,0,1,2,3,4,5,6,7,8,9,...,13,14,15,16,17,18,19,20,21,22
0,0.000112,0.004125,0.000030,0.000930,0.021529,0.028928,0.020979,0.139992,0.363763,0.142592,...,0.000004,0.000002,0.000002,0.000002,0.000004,0.000004,0.000003,0.000001,0.000001,0.000002
1,0.000144,0.016062,0.000124,0.020930,0.035410,0.036026,0.035804,0.136871,0.312255,0.165834,...,0.000006,0.000003,0.000003,0.000003,0.000006,0.000005,0.000004,0.000002,0.000002,0.000003
2,0.000108,0.020600,0.000106,0.016764,0.040742,0.037640,0.031011,0.143877,0.307626,0.167265,...,0.000005,0.000002,0.000003,0.000003,0.000004,0.000004,0.000004,0.000002,0.000002,0.000003
3,0.000119,0.021160,0.000100,0.013560,0.042193,0.043631,0.023475,0.148299,0.302112,0.171456,...,0.000005,0.000002,0.000003,0.000003,0.000003,0.000004,0.000003,0.000002,0.000002,0.000002
4,0.000133,0.013069,0.000070,0.010709,0.040243,0.045494,0.017602,0.144948,0.328284,0.157834,...,0.000006,0.000002,0.000003,0.000003,0.000003,0.000004,0.000003,0.000002,0.000002,0.000002

In [94]:
pos_preds_df.head()

,0,1,2,3,4,5,6,7,8,9,...,13,14,15,16,17,18,19,20,21,22
0,1.640726e-07,0.178307,0.062233,0.045381,0.014883,0.051346,0.001692,0.192988,0.053921,0.110438,...,1.393491e-07,1.361313e-07,1.382227e-07,1.390481e-07,1.373405e-07,1.353630e-07,1.353255e-07,1.391849e-07,1.391082e-07,1.392530e-07
1,1.736712e-07,0.155908,0.059429,0.048761,0.019745,0.051291,0.001868,0.187562,0.054593,0.117082,...,1.418552e-07,1.387396e-07,1.407648e-07,1.416193e-07,1.399268e-07,1.377342e-07,1.379198e-07,1.417979e-07,1.416708e-07,1.418046e-07
2,1.937645e-07,0.175763,0.045544,0.037266,0.022092,0.050813,0.001980,0.179007,0.063216,0.112996,...,1.510694e-07,1.480029e-07,1.498645e-07,1.509057e-07,1.493005e-07,1.461740e-07,1.469696e-07,1.510936e-07,1.510381e-07,1.510497e-07
3,2.415866e-07,0.173709,0.015175,0.028011,0.021497,0.045071,0.001803,0.184161,0.069956,0.123087,...,1.804153e-07,1.778352e-07,1.796831e-07,1.804559e-07,1.796833e-07,1.736766e-07,1.761069e-07,1.807015e-07,1.808267e-07,1.804630e-07
4,3.041023e-07,0.166131,0.003883,0.023011,0.021302,0.032591,0.001434,0.182751,0.087687,0.128344,...,2.160719e-07,2.138065e-07,2.158252e-07,2.164049e-07,2.166153e-07,2.065861e-07,2.110420e-07,2.166797e-07,2.170450e-07,2.162419e-07

In [93]:
pos_pred.shape

pos_preds_df = pd.DataFrame(pos_pred.cpu())
hw_pred_df = pd.DataFrame(hw_pred.cpu())

pos_preds_df.to_csv("pos_preds_df.csv",index=False)
hw_pred_df.to_csv("hw_pred_df.csv",index=False)
pd.Series(player_ids).to_csv("player_ids.csv",index=False)

In [60]:
pd.Series(player_ids)

0        -1
1     35493
2     42406
3     43326
4     46137
5     47846
6     47984
7     52546
8     52792
9     53487
10    54527
11    54708
12    25511
13    38947
14    41233
15    42377
16    42474
17    44816
18    46263
19    52421
20    53524
21    54522
22    54571
dtype: int32

In [52]:
pos_preds_df = pd.DataFrame(pos_pred.cpu())

ValueError: Length of values (23) does not match length of index (32)

In [35]:
hw_preds_df = pd.DataFrame(hw_pred.cpu())
hw_preds_df['player_id'] = player_ids
hw_preds_df['model'] = 'Height_and_Weight'
hw_preds_df['time'] = hw_preds_df.index+1

In [40]:
all_preds_df = pd.concat([pos_preds_df, hw_preds_df],axis=0)

In [45]:
all_preds_df.to_csv("all_preds_df.csv",index=False)

In [46]:
all_preds_df.head()

,-1,35493,42406,43326,46137,47846,47984,52546,52792,53487,...,42377,42474,44816,46263,52421,53524,54522,54571,Model,time
0,1.640726e-07,0.178307,0.062233,0.045381,0.014883,0.051346,0.001692,0.192988,0.053921,0.110438,...,1.382227e-07,1.390481e-07,1.373405e-07,1.353630e-07,1.353255e-07,1.391849e-07,1.391082e-07,1.392530e-07,Position,1
1,1.736712e-07,0.155908,0.059429,0.048761,0.019745,0.051291,0.001868,0.187562,0.054593,0.117082,...,1.407648e-07,1.416193e-07,1.399268e-07,1.377342e-07,1.379198e-07,1.417979e-07,1.416708e-07,1.418046e-07,Position,2
2,1.937645e-07,0.175763,0.045544,0.037266,0.022092,0.050813,0.001980,0.179007,0.063216,0.112996,...,1.498645e-07,1.509057e-07,1.493005e-07,1.461740e-07,1.469696e-07,1.510936e-07,1.510381e-07,1.510497e-07,Position,3
3,2.415866e-07,0.173709,0.015175,0.028011,0.021497,0.045071,0.001803,0.184161,0.069956,0.123087,...,1.796831e-07,1.804559e-07,1.796833e-07,1.736766e-07,1.761069e-07,1.807015e-07,1.808267e-07,1.804630e-07,Position,4
4,3.041023e-07,0.166131,0.003883,0.023011,0.021302,0.032591,0.001434,0.182751,0.087687,0.128344,...,2.158252e-07,2.164049e-07,2.166153e-07,2.065861e-07,2.110420e-07,2.166797e-07,2.170450e-07,2.162419e-07,Position,5